# Generated by Django 4.1.3 on 2022-12-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='title',
            new_name='name',
        ),
    ]
